### ISSUE TITLE
how to set a user admin/mod on web interface of rethinkdb

### ISSUE THREAD

**Issue by HiiZun** [discordboats-club/website#3]
all is in the title

**Comment by PhoenixOnARoof** [comment]
> all is in the title

I don't have an example to show anymore but it's done by adding `admin: true` or `mod: true` to the target user id in the users table

**Comment by HiiZun** [comment]
that is my problem. what is the command to add it

http://prntscr.com/pxwm08

i'm bad to rethinkdb

**Comment by PhoenixOnARoof** [comment]
> that is my problem. what is the command to add it
> 
> http://prntscr.com/pxwm08
> 
> i'm bad to rethinkdb

I never used the default admin interface because it's just a viewer it doesn't allow you to change (easily) I used a third party interface called "Chateau"

**Comment by HiiZun** [comment]
okay i go try it

**Comment by HiiZun** [comment]
i have started a instance of chateau at the port 3060
![image](https://user-images.githubusercontent.com/44111470/68998785-11ddb000-08b7-11ea-8157-2263d82aedda.png) but when i go to the url (vpsip:3060) i have nothing
![image](https://user-images.githubusercontent.com/44111470/68998803-48b3c600-08b7-11ea-9c59-f56a629e8195.png)

**Comment by PhoenixOnARoof** [comment]
> i have started a instance of chateau at the port 3060
> ![image](https://user-images.githubusercontent.com/44111470/68998785-11ddb000-08b7-11ea-8157-2263d82aedda.png) but when i go to the url (vpsip:3060) i have nothing
> ![image](https://user-images.githubusercontent.com/44111470/68998803-48b3c600-08b7-11ea-9c59-f56a629e8195.png)

I can't really help you with that, I don't recall how I setup Chateau.

**Comment by HiiZun** [comment]
personally i have installed by cloning the repo
![image](https://user-images.githubusercontent.com/44111470/68998835-c972c200-08b7-11ea-855a-86e18c6c93d3.png)

**Comment by HiiZun** [comment]
good I thought a lot and I think I prefer to use the native interface rethinkDB and unfortunately we come across the same question: how to insert this document in this table

**Comment by HiiZun** [comment]
i have tried that but this don't work
![image](https://user-images.githubusercontent.com/44111470/69009596-ffb34e80-0956-11ea-8c91-24ee99f5f9f6.png)

**Comment by HiiZun** [comment]
hey i have gess how to add it with:
`r.db("discordboatsclubv1").table("users").get("355995885085392896").update({
  "admin":"true"
})`

but i have another error: https://imgur.com/a/3xtH9bd
